export const lesson12 = {
  id: 12,
  title: "Урок 14: Новые слова и выражения",
  levels: {
    level1: {
      title: "Уровень 1",
      matching: {
        title: "Мэтчинг",
        items: [
          { german: "der Montag", russian: "понедельник" },
          { german: "der Dienstag", russian: "вторник" },
          { german: "der Erste", russian: "первый" },
          { german: "das Datum, die Daten", russian: "дата, даты" },
          { german: "das Fenster", russian: "окно" },
          { german: "das Zimmer", russian: "комната" },
          { german: "der Tisch", russian: "стол" },
          { german: "die Küche", russian: "кухня" },
          { german: "die Wohnung", russian: "квартира" },
          { german: "der Fußbodenbelag", russian: "линолеум" },
        ],
      },
      puzzle: { title: "Пазл", items: [] },
      text: { title: "Заполните пропуск", items: [] },
      typing: {
        title: "Проверка написания",
        items: [
          {
            german: "der Montag",
            russian: "понедельник",
            content: "der Montag",
          },
          {
            german: "der Dienstag",
            russian: "вторник",
            content: "der Dienstag",
          },
          { german: "der Erste", russian: "первый", content: "der Erste" },
          { german: "das Datum", russian: "дата, даты", content: "das Datum" },
          { german: "das Fenster", russian: "окно", content: "das Fenster" },
          { german: "das Zimmer", russian: "комната", content: "das Zimmer" },
          { german: "der Tisch", russian: "стол", content: "der Tisch" },
          { german: "die Küche", russian: "кухня", content: "die Küche" },
          {
            german: "die Wohnung",
            russian: "квартира",
            content: "die Wohnung",
          },
          {
            german: "der Fußbodenbelag",
            russian: "линолеум",
            content: "der Fußbodenbelag",
          },
        ],
      },
    },

    level2: {
      title: "Уровень 2",
      matching: {
        title: "Мэтчинг",
        items: [
          { german: "mitnehmen", russian: "брать с собой" },
          { german: "kaufen", russian: "покупать" },
          { german: "angucken", russian: "глядеть" },
          { german: "sollen", russian: "быть обязанным, быть должным" },
          { german: "hingucken", russian: "смотреть" },
          { german: "warten", russian: "ждать" },
          { german: "suchen", russian: "искать" },
          { german: "mitbringen", russian: "приносить с собой" },
          { german: "sich bemühen", russian: "стараться" },
          { german: "von", russian: "от, из" },
        ],
      },
      puzzle: { title: "Пазл", items: [] },
      text: { title: "Заполните пропуск", items: [] },
      typing: {
        title: "Проверка написания",
        items: [
          {
            german: "mitnehmen",
            russian: "брать с собой",
            content: "mitnehmen",
          },
          { german: "kaufen", russian: "покупать", content: "kaufen" },
          { german: "angucken", russian: "глядеть", content: "angucken" },
          {
            german: "sollen",
            russian: "быть обязанным, быть должным",
            content: "sollen",
          },
          { german: "hingucken", russian: "смотреть", content: "hingucken" },
          { german: "warten", russian: "ждать", content: "warten" },
          { german: "suchen", russian: "искать", content: "suchen" },
          {
            german: "mitbringen",
            russian: "приносить с собой",
            content: "mitbringen",
          },
          {
            german: "sich bemühen",
            russian: "стараться",
            content: "sich bemühen",
          },
          { german: "von", russian: "от, из", content: "von" },
        ],
      },
    },

    level3: {
      title: "Уровень 3",
      matching: {
        title: "Мэтчинг",
        items: [
          { german: "in", russian: "в" },
          { german: "bis", russian: "до" },
          { german: "zu", russian: "к" },
          { german: "um", russian: "около" },
          { german: "nach", russian: "после" },
          { german: "für", russian: "для, за" },
          { german: "oder", russian: "или, либо" },
          { german: "mit", russian: "с" },
          { german: "ab", russian: "начиная с" },
          { german: "sozusagen", russian: "так сказать" },
          { german: "übrigens", russian: "кстати, к слову" },
          { german: "wahrscheinlich", russian: "вероятно" },
          { german: "offen gesagt", russian: "откровенно говоря" },
          { german: "ehrlich gesagt", russian: "честно говоря" },
          { german: "außerdem", russian: "кроме того" },
          { german: "überhaupt", russian: "вообще" },
          { german: "auf jeden Fall", russian: "в любом случае" },
          {
            german: "es versteht sich von selbst",
            russian: "само собой разумеется",
          },
          { german: "möglicherweise", russian: "может быть" },
        ],
      },
      puzzle: { title: "Пазл", items: [] },
      text: { title: "Заполните пропуск", items: [] },
      typing: {
        title: "Проверка написания",
        items: [
          { german: "in", russian: "в", content: "in" },
          { german: "bis", russian: "до", content: "bis" },
          { german: "zu", russian: "к", content: "zu" },
          { german: "um", russian: "около", content: "um" },
          { german: "nach", russian: "после", content: "nach" },
          { german: "für", russian: "для, за", content: "für" },
          { german: "oder", russian: "или, либо", content: "oder" },
          { german: "mit", russian: "с", content: "mit" },
          { german: "ab", russian: "начиная с", content: "ab" },
          { german: "sozusagen", russian: "так сказать", content: "sozusagen" },
          {
            german: "übrigens",
            russian: "кстати, к слову",
            content: "übrigens",
          },
          {
            german: "wahrscheinlich",
            russian: "вероятно",
            content: "wahrscheinlich",
          },
          {
            german: "offen gesagt",
            russian: "откровенно говоря",
            content: "offen gesagt",
          },
          {
            german: "ehrlich gesagt",
            russian: "честно говоря",
            content: "ehrlich gesagt",
          },
          { german: "außerdem", russian: "кроме того", content: "außerdem" },
          { german: "überhaupt", russian: "вообще", content: "überhaupt" },
          {
            german: "auf jeden Fall",
            russian: "в любом случае",
            content: "auf jeden Fall",
          },
          {
            german: "es versteht sich von selbst",
            russian: "само собой разумеется",
            content: "es versteht sich von selbst",
          },
          {
            german: "möglicherweise",
            russian: "может быть",
            content: "möglicherweise",
          },
        ],
      },
    },
  },
  audio: {
    title: "Аудирование",
    src: "/audio/lesson10.mp3",
  },
};
