export const lesson11 = {
  id: 11,
  title: "Урок 13: Новые слова",
  levels: {
    level1: {
      title: "Уровень 1",
      matching: {
        title: "Мэтчинг",
        items: [
          { german: "euer", russian: "ваш" },
          { german: "an", russian: "на" },
          { german: "bei", russian: "у" },
          { german: "seit", russian: "с (с каких-то пор)" },
          { german: "das", russian: "это" },
          { german: "sich", russian: "себя" },
          { german: "etwas", russian: "что-то" },
          { german: "jemand", russian: "кто-нибудь, кто-то" },
          { german: "welcher", russian: "который, какой" },
          { german: "dieser", russian: "этот" },
        ],
      },
      puzzle: { title: "Пазл", items: [] },
      text: { title: "Заполните пропуск", items: [] },
      typing: {
        title: "Проверка написания",
        items: [
          { german: "euer", russian: "ваш", content: "euer" },
          { german: "an", russian: "на", content: "an" },
          { german: "bei", russian: "у", content: "bei" },
          { german: "seit", russian: "с (с каких-то пор)", content: "seit" },
          { german: "das", russian: "это", content: "das" },
          { german: "sich", russian: "себя", content: "sich" },
          { german: "etwas", russian: "что-то", content: "etwas" },
          {
            german: "jemand",
            russian: "кто-нибудь, кто-то",
            content: "jemand",
          },
          { german: "welcher", russian: "который, какой", content: "welcher" },
          { german: "dieser", russian: "этот", content: "dieser" },
        ],
      },
    },

    level2: {
      title: "Уровень 2",
      matching: {
        title: "Мэтчинг",
        items: [
          { german: "stehen", russian: "стоять" },
          { german: "bringen", russian: "приносить" },
          { german: "vorkommen", russian: "происходить, случаться" },
          { german: "umziehen", russian: "переезжать" },
          { german: "besuchen", russian: "посещать, навещать" },
          { german: "wohnen", russian: "жить" },
          { german: "ausverkaufen", russian: "распродавать" },
          { german: "aufwachsen", russian: "вырасти" },
          { german: "die Freizeit", russian: "свободное время" },
          { german: "verkaufen", russian: "продавать" },
        ],
      },
      puzzle: { title: "Пазл", items: [] },
      text: { title: "Заполните пропуск", items: [] },
      typing: {
        title: "Проверка написания",
        items: [
          { german: "stehen", russian: "стоять", content: "stehen" },
          { german: "bringen", russian: "приносить", content: "bringen" },
          {
            german: "vorkommen",
            russian: "происходить, случаться",
            content: "vorkommen",
          },
          { german: "umziehen", russian: "переезжать", content: "umziehen" },
          {
            german: "besuchen",
            russian: "посещать, навещать",
            content: "besuchen",
          },
          { german: "wohnen", russian: "жить", content: "wohnen" },
          {
            german: "ausverkaufen",
            russian: "распродавать",
            content: "ausverkaufen",
          },
          { german: "aufwachsen", russian: "вырасти", content: "aufwachsen" },
          {
            german: "die Freizeit",
            russian: "свободное время",
            content: "die Freizeit",
          },
          { german: "verkaufen", russian: "продавать", content: "verkaufen" },
        ],
      },
    },

    level3: {
      title: "Уровень 3",
      matching: {
        title: "Мэтчинг",
        items: [
          { german: "die Minute, die Minuten", russian: "минута" },
          { german: "der Moment", russian: "данное время, сейчас" },
          { german: "der Sommer", russian: "лето" },
          { german: "der Monat", russian: "месяц" },
          { german: "der Zeitraum", russian: "период времени" },
          { german: "das Wochenende", russian: "конец недели" },
          { german: "die Zukunft", russian: "будущее" },
          { german: "der Abend", russian: "вечер" },
          { german: "der Mittag", russian: "полдень" },
          { german: "Deutschunterricht", russian: "урок немецкого языка" },
          { german: "der Geburtstag", russian: "день рождения" },
          { german: "die Idee", russian: "идея" },
          { german: "das Ende", russian: "конец" },
          { german: "die Tochter", russian: "дочь" },
          { german: "frühstücken", russian: "завтракать" },
          { german: "der Nachmittag", russian: "после обеда" },
          { german: "die Schuhe", russian: "обувь" },
          { german: "oft", russian: "часто" },
          { german: "spielen", russian: "играть" },
          { german: "der Film", russian: "фильм" },
        ],
      },
      puzzle: { title: "Пазл", items: [] },
      text: { title: "Заполните пропуск", items: [] },
      typing: {
        title: "Проверка написания",
        items: [
          {
            german: "die Minute, die Minuten",
            russian: "минута",
            content: "die Minute",
          },
          {
            german: "der Moment",
            russian: "данное время, сейчас",
            content: "der Moment",
          },
          { german: "der Sommer", russian: "лето", content: "der Sommer" },
          { german: "der Monat", russian: "месяц", content: "der Monat" },
          {
            german: "der Zeitraum",
            russian: "период времени",
            content: "der Zeitraum",
          },
          {
            german: "das Wochenende",
            russian: "конец недели",
            content: "das Wochenende",
          },
          { german: "die Zukunft", russian: "будущее", content: "die Zukunft" },
          { german: "der Abend", russian: "вечер", content: "der Abend" },
          { german: "der Mittag", russian: "полдень", content: "der Mittag" },
          {
            german: "Deutschunterricht",
            russian: "урок немецкого языка",
            content: "Deutschunterricht",
          },
          {
            german: "der Geburtstag",
            russian: "день рождения",
            content: "der Geburtstag",
          },
          { german: "die Idee", russian: "идея", content: "die Idee" },
          { german: "das Ende", russian: "конец", content: "das Ende" },
          { german: "die Tochter", russian: "дочь", content: "die Tochter" },
          {
            german: "frühstücken",
            russian: "завтракать",
            content: "frühstücken",
          },
          {
            german: "der Nachmittag",
            russian: "после обеда",
            content: "der Nachmittag",
          },
          { german: "die Schuhe", russian: "обувь", content: "die Schuhe" },
          { german: "oft", russian: "часто", content: "oft" },
          { german: "spielen", russian: "играть", content: "spielen" },
          { german: "der Film", russian: "фильм", content: "der Film" },
        ],
      },
    },
  },
  audio: {
    title: "Аудирование",
    src: "/audio/lesson9.mp3",
  },
};
