export const lesson14 = {
  id: 14,
  title: "Урок 19: Новые слова и выражения",
  levels: {
    level1: {
      title: "Уровень 1",
      matching: {
        title: "Мэтчинг",
        items: [
          {
            german: "das Studentenwohnheim",
            russian: "студенческое общежитие",
          },
          { german: "das Fach, die Fächer", russian: "учебный предмет" },
          { german: "die Spezialität", russian: "специальность" },
          { german: "der Master", russian: "магистр" },
          { german: "der Plan, Pläne", russian: "план" },
          { german: "das College", russian: "колледж" },
          {
            german: "die Fachschule",
            russian: "техникум, колледж, профессиональное училище",
          },
          { german: "die Akademie", russian: "академия" },
          { german: "PhD", russian: "степень кандидата наук" },
          { german: "sich vorbereiten", russian: "подготовиться" },
        ],
      },
      puzzle: { title: "Пазл", items: [] },
      text: { title: "Заполните пропуск", items: [] },
      typing: {
        title: "Проверка написания",
        items: [
          {
            german: "das Studentenwohnheim",
            russian: "студенческое общежитие",
            content: "das Studentenwohnheim",
          },
          {
            german: "das Fach",
            russian: "учебный предмет",
            content: "das Fach",
          },
          {
            german: "die Spezialität",
            russian: "специальность",
            content: "die Spezialität",
          },
          { german: "der Master", russian: "магистр", content: "der Master" },
          { german: "der Plan", russian: "план", content: "der Plan" },
          { german: "das College", russian: "колледж", content: "das College" },
          {
            german: "die Fachschule",
            russian: "техникум, колледж, профессиональное училище",
            content: "die Fachschule",
          },
          {
            german: "die Akademie",
            russian: "академия",
            content: "die Akademie",
          },
          { german: "PhD", russian: "степень кандидата наук", content: "PhD" },
          {
            german: "sich vorbereiten",
            russian: "подготовиться",
            content: "sich vorbereiten",
          },
        ],
      },
    },

    level2: {
      title: "Уровень 2",
      matching: {
        title: "Мэтчинг",
        items: [
          { german: "gründen", russian: "основывать" },
          { german: "finden", russian: "находить, считать" },
          { german: "servieren", russian: "подавать на стол" },
          {
            german: "schaffen",
            russian: "создавать, творить, справляться с чем-то",
          },
          { german: "moderieren", russian: "вести передачу" },
          { german: "organiesieren", russian: "организовать" },
          { german: "sollen", russian: "быть обязанным, быть должным" },
          { german: "verdienen", russian: "зарабатывать, заслужить" },
          { german: "klappen", russian: "получаться" },
          { german: "so", russian: "так" },
          { german: "heute", russian: "сегодня" },
          { german: "bisschen", russian: "немного, чуть-чуть" },
          { german: "anders", russian: "по-другому" },
          { german: "gleich", russian: "сейчас, немедленно, одинаковый" },
        ],
      },
      puzzle: { title: "Пазл", items: [] },
      text: { title: "Заполните пропуск", items: [] },
      typing: {
        title: "Проверка написания",
        items: [
          { german: "gründen", russian: "основывать", content: "gründen" },
          { german: "finden", russian: "находить, считать", content: "finden" },
          {
            german: "servieren",
            russian: "подавать на стол",
            content: "servieren",
          },
          {
            german: "schaffen",
            russian: "создавать, творить, справляться с чем-то",
            content: "schaffen",
          },
          {
            german: "moderieren",
            russian: "вести передачу",
            content: "moderieren",
          },
          {
            german: "organiesieren",
            russian: "организовать",
            content: "organiesieren",
          },
          {
            german: "sollen",
            russian: "быть обязанным, быть должным",
            content: "sollen",
          },
          {
            german: "verdienen",
            russian: "зарабатывать, заслужить",
            content: "verdienen",
          },
          { german: "klappen", russian: "получаться", content: "klappen" },
          { german: "so", russian: "так", content: "so" },
          { german: "heute", russian: "сегодня", content: "heute" },
          {
            german: "bisschen",
            russian: "немного, чуть-чуть",
            content: "bisschen",
          },
          { german: "anders", russian: "по-другому", content: "anders" },
          {
            german: "gleich",
            russian: "сейчас, немедленно, одинаковый",
            content: "gleich",
          },
        ],
      },
    },

    level3: {
      title: "Уровень 3",
      matching: {
        title: "Мэтчинг",
        items: [
          { german: "soweit", russian: "насколько" },
          { german: "miteinander", russian: "друг с другом" },
          { german: "beide", russian: "оба, обе" },
          { german: "sofort", russian: "немедленно" },
          { german: "oft", russian: "часто" },
          { german: "die Studentenstadt", russian: "университетский город" },
          { german: "die Vorteile", russian: "преимущества" },
          { german: "die Nachteile", russian: "недостатки" },
          { german: "ausserdem", russian: "кроме того" },
          { german: "im Mittelpunkt", russian: "в центре внимания" },
          { german: "sowieso", russian: "всё равно, так или иначе" },
          { german: "klipp und klar", russian: "коротко и ясно" },
          { german: "je ... desto", russian: "чем ... тем" },
          { german: "am Anfang", russian: "в начале" },
          { german: "im Gegensatz zu", russian: "в отличие от" },
          { german: "eigentlich", russian: "собственно" },
        ],
      },
      puzzle: { title: "Пазл", items: [] },
      text: { title: "Заполните пропуск", items: [] },
      typing: {
        title: "Проверка написания",
        items: [
          { german: "soweit", russian: "насколько", content: "soweit" },
          {
            german: "miteinander",
            russian: "друг с другом",
            content: "miteinander",
          },
          { german: "beide", russian: "оба, обе", content: "beide" },
          { german: "sofort", russian: "немедленно", content: "sofort" },
          { german: "oft", russian: "часто", content: "oft" },
          {
            german: "die Studentenstadt",
            russian: "университетский город",
            content: "die Studentenstadt",
          },
          {
            german: "die Vorteile",
            russian: "преимущества",
            content: "die Vorteile",
          },
          {
            german: "die Nachteile",
            russian: "недостатки",
            content: "die Nachteile",
          },
          { german: "ausserdem", russian: "кроме того", content: "ausserdem" },
          {
            german: "im Mittelpunkt",
            russian: "в центре внимания",
            content: "im Mittelpunkt",
          },
          {
            german: "sowieso",
            russian: "всё равно, так или иначе",
            content: "sowieso",
          },
          {
            german: "klipp und klar",
            russian: "коротко и ясно",
            content: "klipp und klar",
          },
          {
            german: "je ... desto",
            russian: "чем ... тем",
            content: "je ... desto",
          },
          { german: "am Anfang", russian: "в начале", content: "am Anfang" },
          {
            german: "im Gegensatz zu",
            russian: "в отличие от",
            content: "im Gegensatz zu",
          },
          {
            german: "eigentlich",
            russian: "собственно",
            content: "eigentlich",
          },
        ],
      },
    },
    level4: {
      title: "Уровень 4",
      matching: {
        title: "Мэтчинг",
        items: [
          { german: "jeder Mensch", russian: "каждый человек" },
          {
            german: "es gibt über 200 Sprachen in der Welt",
            russian: "в мире есть более 200 языков",
          },
          { german: "offizielle Sprache", russian: "официальный язык" },
          { german: "sich grenzen", russian: "ограничиться" },
          { german: "merken", russian: "замечать" },
          { german: "Hochkirgisisch", russian: "литературный кыргызский" },
          { german: "ab 4.Klasse", russian: "с 4го класса" },
          { german: "Englischunterricht", russian: "урок английского" },
          { german: "sich entscheiden", russian: "решаться" },
          { german: "denken (dachte)", russian: "думать" },
          { german: "wie Muttersprache", russian: "как родной язык" },
          { german: "sich faszinieren", russian: "очаровывать, околдовывать" },
          { german: "mitsingen", russian: "петь вместе" },
          {
            german: "der Inhalt, die Inhalte",
            russian: "содержание, содержимое",
          },
          {
            german: "Deutsch ist schwieriger als Englisch",
            russian: "немецкий сложнее чем английский",
          },
          { german: "die Sendung", russian: "передача" },
          { german: "beherrschen", russian: "владеть, знать в совершенстве" },
          { german: "unglaublich", russian: "невероятный, невообразимый" },
          { german: "mithilfe", russian: "с помощью" },
          { german: "zusätzlich", russian: "дополнительно" },
          { german: "empfehlen", russian: "рекомендовать" },
          { german: "nicht genug", russian: "недостаточно" },
          { german: "der Wortschatz", russian: "словарный запас" },
          { german: "interessante Dinge", russian: "интересные вещи" },
        ],
      },
      puzzle: { title: "Пазл", items: [] },
      text: { title: "Заполните пропуск", items: [] },
      typing: {
        title: "Проверка написания",
        items: [
          {
            german: "jeder Mensch",
            russian: "каждый человек",
            content: "jeder Mensch",
          },
          {
            german: "es gibt über 200 Sprachen in der Welt",
            russian: "в мире есть более 200 языков",
            content: "es gibt über 200 Sprachen in der Welt",
          },
          {
            german: "offizielle Sprache",
            russian: "официальный язык",
            content: "offizielle Sprache",
          },
          {
            german: "sich grenzen",
            russian: "ограничиться",
            content: "sich grenzen",
          },
          { german: "merken", russian: "замечать", content: "merken" },
          {
            german: "Hochkirgisisch",
            russian: "литературный кыргызский",
            content: "Hochkirgisisch",
          },
          {
            german: "ab 4.Klasse",
            russian: "с 4го класса",
            content: "ab 4.Klasse",
          },
          {
            german: "Englischunterricht",
            russian: "урок английского",
            content: "Englischunterricht",
          },
          {
            german: "sich entscheiden",
            russian: "решаться",
            content: "sich entscheiden",
          },
          {
            german: "denken (dachte)",
            russian: "думать",
            content: "denken (dachte)",
          },
          {
            german: "wie Muttersprache",
            russian: "как родной язык",
            content: "wie Muttersprache",
          },
          {
            german: "sich faszinieren",
            russian: "очаровывать, околдовывать",
            content: "sich faszinieren",
          },
          { german: "mitsingen", russian: "петь вместе", content: "mitsingen" },
          {
            german: "der Inhalt, die Inhalte",
            russian: "содержание, содержимое",
            content: "der Inhalt",
          },
          {
            german: "Deutsch ist schwieriger als Englisch",
            russian: "немецкий сложнее чем английский",
            content: "Deutsch ist schwieriger als Englisch",
          },
          {
            german: "die Sendung",
            russian: "передача",
            content: "die Sendung",
          },
          {
            german: "beherrschen",
            russian: "владеть, знать в совершенстве",
            content: "beherrschen",
          },
          {
            german: "unglaublich",
            russian: "невероятный, невообразимый",
            content: "unglaublich",
          },
          { german: "mithilfe", russian: "с помощью", content: "mithilfe" },
          {
            german: "zusätzlich",
            russian: "дополнительно",
            content: "zusätzlich",
          },
          {
            german: "empfehlen",
            russian: "рекомендовать",
            content: "empfehlen",
          },
          {
            german: "nicht genug",
            russian: "недостаточно",
            content: "nicht genug",
          },
          {
            german: "der Wortschatz",
            russian: "словарный запас",
            content: "der Wortschatz",
          },
          {
            german: "interessante Dinge",
            russian: "интересные вещи",
            content: "interessante Dinge",
          },
        ],
      },
    },
  },
  audio: {
    title: "Аудирование",
    src: "/audio/lesson11.mp3",
  },
};
